CREATE TABLE TRENDING_MOVIES(
MOVIE_ID INT PRIMARY KEY,
TITLE VARCHAR(255),
RELEASE_DATE date,
POPULARITY FLOAT,
VOTE_AVERAGE FLOAT,
VOTE_COUNT INT
);
use streaming_project;
SELECT * FROM TRENDING_MOVIES;